travis:
  secure:
    BINSTAR_TOKEN: ACOg7Ju4q/A4tWkV3qx/D/sH40coEPkYA9DJPkCLSW/W51bxWErRby44mEjPkkHVQJvysbmOTPZWyG6VTB6H6jjbSjbJiYj6FKatqqwv+oRFlrEbbLuI/LEeRICZ96sDO0Ucj4YgBZdM5cJiS5CoigatUVESH5YBpU7DXLODw/EBYtNyGORskBKUEICV+jL0mWKAMoArTyyhf2BR2ymMSPVbnzVrNvDWk0Peshii1wGAf2rdrWUQb9D79s0fJFJHZuA54kiJwNqh7tAIJeRq5YnQEBNdFT2PQLuMO1882YH+cn5YMO55Yeg2y7hph/XeRiMf3xvdUjc78ZRvSa4MHAMWnNGdJ+xDZY9HDH04vKAoS7ebWikZyMJyR6GBteslcTPpdDnfzzX2Fq/u0sjpuTtomdPadzsrw7XHnNIRtzm6b1EziCYWVXvTR4H9IQiFXcd4Y1KT3qEilOE+xoFqlnIqa3qs979lDi1yzSAaFM1XpzIJwrxzs27OYT944uI6b3OYFv8162GwjeImeJt51bTEPMY+AZqLX/y0/qo2E2HToQwAogrFyBj6Mrdq20VsphiCyyZDAeHF4zyrwSu8NieiSd0qdCacSojmeE928x1u19EoZv9Xf7pFyjDSMHLzKiEX2L4TSrCx5lJXBoLveNsspA7CnAASA9AhopyJ7Pw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
